### ISSUE TITLE
Node-red-contrib-re-postgres does not work on android-termux

### ISSUE THREAD

**Issue by LorenzoISF** [unirobot/node-red-contrib-postgres#12]
Morning,
I'm using an architecture based on node-red and postgresql to be used indifferently for various platforms: windows, raspberry, cloud and android (termux). On android-termux the postgresql db works, but on node-red the node-red-contrib-re-postgres node doesn't work; even if I insert messages, the node doesn't show any sign of life. I specify that making cross platform node-red(windows) and postgresql(android), it works.
Greetings.
Lorenzo

**Comment by LorenzoISF** [comment]
I am using noroot device.

**Comment by okhiroyuki** [comment]
Hi, @LorenzoISF 

This is not the node-red the node-red-contrib-re-postgres repository.
You should not create an issue here for a different repository.
